name: Deploy to Hetzner

on:
  push:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: true
        default: "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy to Hetzner
          run: |
            BRANCH="${{ github.event.inputs.branch || github.ref_name }}"
            ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
              cd /var/www/myapp &&
              git fetch origin $BRANCH &&
              git checkout $BRANCH &&
              git pull origin $BRANCH &&
              npm install --production &&
              pm2 restart myapp
            "
