name: Deploy to Hetzner

on:
  push:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: true
        default: "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

        - name: Copy n8n-docker-caddy folder to server
          run: |
            scp -o StrictHostKeyChecking=no -r n8n-docker-caddy ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/n8n/n8n-docker-caddy

      - name: Deploy to Hetzner
        run: |
          BRANCH="${{ github.event.inputs.branch || github.ref_name }}"
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} bash -s << 'EOF'
            cd /var/www/n8n
            git fetch origin $BRANCH
            git checkout $BRANCH
            git pull origin $BRANCH
              cd n8n-docker-caddy/
              docker compose down
              docker compose up -d --build
          EOF
