name: Deploy Folder to Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy folder via rsync
        run: |
         rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./n8n-docker-caddy/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/n8n/
      - name: Restart services on server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            cd /n8n/ &&
            docker compose down &&
            docker compose up -d --build
          "