name: Playwright Scraper

on:
  workflow_dispatch:
    inputs:
      SCRAPER_URL:
        description: 'URL to scrape'
        required: false
        default: 'https://www.sreality.cz/hledani/pronajem/byty/praha?velikost=3%2Bkk'

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Ensure package-lock.json exists
        run: |
          if [ ! -f package-lock.json ]; then
            npm install --package-lock-only
          fi

      - name: Cache Node.js dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-${{ runner.os }}-

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: |
          npm init -y # Create package.json if it doesn't exist
          npm install playwright archiver # Install Playwright and archiver for zipping
          npx playwright install --with-deps # Install Playwright browsers with dependencies

      - name: Run scraper
        run: node scripts/scraper.js
        env:
          CI: true # Ensure Playwright runs in CI mode
          SCRAPER_URL: ${{ github.event.inputs.SCRAPER_URL }}

      - name: Upload scraped results
        uses: actions/upload-artifact@v4
        with:
          name: scraped-results
          path: scripts/results.zip

      - name: Upload listing images
        uses: actions/upload-artifact@v4
        with:
          name: listing-images
          path: scripts/images.zip