name: Playwright Scraper

on:
  workflow_dispatch:
    inputs:
      SCRAPER_URL:
        description: 'URL to scrape'
        required: false
        default: 'https://www.sreality.cz/hledani/pronajem/byty/praha?velikost=3%2Bkk'

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # -------- Node.js dependencies cache --------
      - name: Cache Node.js dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-modules-${{ runner.os }}-

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install Node.js dependencies
        run: |
          npm ci
          # ensure playwright & archiver are installed (if not listed in package.json)
          npm install --no-audit --no-fund playwright archiver

      # -------- Playwright browsers cache --------
      - name: Cache Playwright browsers
        id: cache-playwright
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright browsers (cache miss)
        if: steps.cache-playwright.outputs.cache-hit != 'true'
        run: |
          echo "Playwright cache miss — installing browsers + system deps"
          npx playwright install --with-deps
        env:
          CI: true

      - name: Ensure Playwright OS deps installed (cache hit)
        if: steps.cache-playwright.outputs.cache-hit == 'true'
        run: |
          echo "Playwright cache hit — ensuring OS dependencies are present"
          npx playwright install-deps || true
        env:
          CI: true

      # Optional debug steps (odkomentuj pro ladění)
      # - name: Debug: print cache hit
      #   run: echo "cache-hit=${{ steps.cache-playwright.outputs.cache-hit }}"
      #
      # - name: Debug: ls playwright cache dir
      #   if: always()
      #   run: |
      #     echo "Listing ~/.cache and ~/.cache/ms-playwright"
      #     ls -la ~/.cache || true
      #     ls -la ~/.cache/ms-playwright || true

      # -------- Run scraper --------
      - name: Run scraper
        run: node scripts/scraper.js
        env:
          CI: true
          SCRAPER_URL: ${{ github.event.inputs.SCRAPER_URL }}

      # -------- Upload results --------
      - name: Upload scraped results
        uses: actions/upload-artifact@v4
        with:
          name: scraped-results
          path: scripts/results.zip
